### ISSUE TITLE
Proposal: Date & Time of generation in header comment in generated files

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#868] opened 2016-08-03 09:27 UTC
What the title says. this would be a nice touch to easily allow the user to check if his generated files are up to date and if the automated building works (it doesn't always). Also, the used version of SCT might be nice, if this can be easily done. Maybe there should be a huge block comment in the top that says "Generated by YAKINDU Statechart Tools 2.7.2 - statecharts.org".

**Comment by terfloth** [comment] 2016-08-30 06:59
* This should be configurable from the sgen file.
* Requires detailed specification

**Comment by andreasmuelder** [comment] 2018-01-02 15:32
Duplicate of #1786

**Closed by andreasmuelder** 2018-01-02 15:32 UTC
Labels: Comp-All Code Generators, is-Feature-Request, Status-Consolidate
