### ISSUE TITLE
(C++ generator) StatemachineInterface.h is not generated in library dir but in output dir

### ISSUE THREAD

**Issue by wixiw** [Yakindu/statecharts#1331] opened 2017-05-01 22:17 UTC
I have an sgen file like this : 

>     statechart FSM_InstallTration {
>         feature Outlet {
>             targetProject = "ard2017_master"
>             targetFolder = "robot/Tration/generated"
>             libraryTargetFolder = "robot/Common/1_RSP/core"
>         }
>     }

The StatemachineInterface.h is generated into robot/Tration/generated whereas I expected him to be in robot/Common/1_RSP/core.

Note that other libraries includes are properly generated in robot/Common/1_RSP/core, in particular TimedStatemachineInterface.h (which is the  StatemachineInterface.h mate file, they should be together).

**Comment by tkutz** [comment] 2017-06-06 07:41
Closing as duplicate of #1406

**Closed by tkutz** 2017-06-06 07:41 UTC
Labels: Comp-CPP Generator, is-Bug
