### ISSUE TITLE
State-local variables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#98] opened 2015-04-24 13:34 UTC
```
Which features should be added?
1. We need Yakindu to support local variables, local to a single state (or a 
single region at least) as opposed to globally visible variables. That's an 
important feature that many users need. Thanks!

```

Original issue reported on code.google.com by `ariana...@gmail.com` on 18 Feb 2015 at 5:56

**Comment by andreasmuelder** [comment] 2018-01-11 11:15
closing as duplicate of https://github.com/Yakindu/sctpro/issues/1178

**Closed by andreasmuelder** 2018-01-11 11:15 UTC
Labels: Comp-Graphical Editor, Prio-Medium, is-Feature-Request
