### ISSUE TITLE
Warning about AbstractLexerBasedConverter

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2565] opened 2019-01-08 10:49 UTC
SCT frequently throws the following warning:
`org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter  - Only terminal rules are supported by lexer based converters but got QID which is an instance of ParserRule`

**Comment by andreasmuelder** [comment] 2019-01-10 13:53
Duplicate of https://github.com/Yakindu/statecharts/issues/2584

**Closed by andreasmuelder** 2019-01-10 13:53 UTC
