### ISSUE TITLE
Validation does not work on synch node within the same region of source or target state

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#82] opened 2015-04-24 13:34 UTC
```
What steps will reproduce the problem?
1. Create an AND state with Sate A in region 1 and state B in region 2
2. Add sync node to region 1 and add transitions from state A and state B to 
sync node 

What is the expected output? What do you see instead?
* the sync node should be valid regarding incoming transitions
* but there is an error marker stating: "The source states of a synchronization 
have to be contained in the same parent state within different regions!"

```

Original issue reported on code.google.com by `AxelTerfloth` on 7 Jan 2015 at 1:24

**Comment by terfloth** [comment] 2015-11-09 13:50
Is a duplicate of #58

**Comment by terfloth** [comment] 2016-03-31 10:47
closed as duplicate

**Closed by terfloth** 2016-03-31 10:47 UTC
Labels: Comp-Validation, is-Bug, Prio-Medium, Status-Duplicate, Status-In Progress
