### ISSUE TITLE
C++ code gets broken two variables like "varName" and "set_varName" are defined

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#1732] opened 2017-10-26 11:14 UTC
For example: Generate c++ code with digital_watch example

or define:
```
var time:integer=0
var set_time:integer=0
```
and generate c++ code

**Comment by tkutz** [comment] 2017-10-26 11:47
Duplicate of https://github.com/Yakindu/statecharts/issues/1595

**Closed** 2017-10-26 11:47 UTC
Labels: Comp-CPP Generator
