### ISSUE TITLE
Domain documentation doesn't always load properly

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2147] opened 2018-07-23 09:12 UTC
See attached screenshot. Steps to reproduce currently not known:

![image](https://user-images.githubusercontent.com/15799654/43067920-3049e2b2-8e69-11e8-88c8-ce2e81b04d72.png)
Switching the domain does not help.

**Comment by tkutz** [comment] 2018-08-27 11:59
I will close this as I cannot reproduce it. Please re-open that issue if you see that behavior again.

**Closed by tkutz** 2018-08-27 11:59 UTC
Labels: Comp-Documentation, Comp-UI
