### ISSUE TITLE
Copying region produces graphic errors

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#831] opened 2016-07-14 09:07 UTC
How to reproduce:

Select main region, copy and paste.

You get some graphic errors like this:

![staircase](https://cloud.githubusercontent.com/assets/15800400/16834139/c5c10ff8-49b2-11e6-89d9-2e65960f697a.jpg)

**Comment by BeckmaR** [comment] 2016-10-18 08:48
Could reproduce, possibly related to #99?

**Comment by svenjawendler** [comment] 2017-05-02 10:19
I cannot reproduce it any more. Close it?

**Comment by BeckmaR** [comment] 2017-07-26 14:00
Issue doesn't seem to be fixed according to #1527.

**Comment by BeckmaR** [comment] 2017-09-11 05:18
Another report: #1639

**Comment by andreasmuelder** [comment] 2018-01-10 15:15
closing as duplicate

**Comment by BeckmaR** [comment] 2018-03-19 10:51
This issue still persists, all other issues related to this are closed, reopening

**Closed** 2020-11-26 18:42 UTC
Labels: Comp-Graphical Editor
