### ISSUE TITLE
Double-clicking on task does not highlight graphical element

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#707] opened 2016-05-23 15:45 UTC
Double-clicking on a statechart task shown in the task view opens the statechart file, if needed, but does not highlight the graphical element defining the task using FIXME or TODO.

**Comment by andreasmuelder** [comment] 2016-05-27 14:36
This is a duplicate of
https://github.com/Yakindu/statecharts/issues/303

**Closed** 2016-05-27 14:36 UTC
Labels: Status-Duplicate
