### ISSUE TITLE
[GUI] action parser refuse lines finishing with ";"

### ISSUE THREAD

**Issue by wixiw** [Yakindu/statecharts#1394] opened 2017-05-24 01:15 UTC
Currently, when I finish a line with a ";" after an action description, the parser generates an error. I would expect the parser to accept the line and consider the ";" as useless but ok. 

Current behavior is annoying because I often add/remove actions during development or use copy/paste to share information between states/transitions. Having to modify the line is painfull and useless. 

I would like to be able to do the following in a state corpus:
```
entry/
action1();
action2();

exit/
action3();
```

It's an edition performance issue, it doesn't prevent the user from reaching his goal.

**Comment by BeckmaR** [comment] 2017-05-24 07:49
Would agree with this. I stumble upon this very often as well and it seems arbitrary. Shouldn't we be able to change this without breaking current statecharts @terfloth?

**Comment by BeckmaR** [comment] 2017-06-13 14:02
Duplicate of #1047, closing.

**Closed by BeckmaR** 2017-06-13 14:02 UTC
Labels: Comp-Other, is-Enhancement
