### ISSUE TITLE
Feature Request: Enable optional ';' at EOF/ last action

### ISSUE THREAD

**Issue by f4l0** [Yakindu/statecharts#2993] opened 2020-02-18 08:45 UTC
Currently you are not allowed to have a "closing" ';' at the last statement/action. To make it more apealing to the user, it would be nice to allow ";" here.

Eg: entry / action1;action2;

**Comment by andreasmuelder** [comment] 2020-02-19 09:20
Closing as duplicate of https://github.com/Yakindu/statecharts/issues/1047

**Closed by andreasmuelder** 2020-02-19 09:20 UTC
