### ISSUE TITLE
JumpTo fails for error 'state must have a name'

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#1321] opened 2017-04-24 12:31 UTC
When SCT errors in the problem view are double-clicked the SCT-editor is opened and the corresponding element is focused.

This feature fails for 'state must have a name' because the focus is set for the states embedded editor instead of the states name text element.

**Comment by andreasmuelder** [comment] 2017-04-24 12:47
closing as a duplicate of https://github.com/Yakindu/statecharts/issues/185

**Closed by andreasmuelder** 2017-04-24 12:47 UTC
