### ISSUE TITLE
Transparency of overlapping regions is strange

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1639] opened 2017-09-08 13:28 UTC
Take a look at this (nonsense) state diagram:
<img width="582" alt="grafik" src="https://user-images.githubusercontent.com/23032586/30213689-20371ef8-94aa-11e7-9551-b701e11a57fc.png">

Now i drag the empty region over that diagram:
<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/23032586/30213739-40b1212e-94aa-11e7-809f-c3daded56067.png">

It looks like the overlapping region is transparent regarding the transitions but not the states. Weird.

**Comment by BeckmaR** [comment] 2017-09-11 05:18
Duplicate of #831, closing

**Closed by BeckmaR** 2017-09-11 05:18 UTC
Labels: Comp-Graphical Editor, is-Usability-Issue
