### ISSUE TITLE
[Simulation] Step over together with @CycleBased does not work

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2340] opened 2018-10-15 13:42 UTC
'Step Over' function for terminated simulations has no effect.

Time will not be proceeded, events will not be handled.

**Comment by andreasmuelder** [comment] 2018-10-18 07:17
This is a duplicate of https://github.com/Yakindu/statecharts/issues/2343
and is fixed with https://github.com/Yakindu/statecharts/pull/2344

**Closed by andreasmuelder** 2018-10-18 07:17 UTC
Labels: Comp-Simulation
