### ISSUE TITLE
Document system requirements in short installation guide

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#712] opened 2016-05-25 09:43 UTC
Besides the comprehensive installation guide, we should have a short overview of the process and dependencies stating the following:

- Current system requirements: JDK 1.8 (and change it to 1.7 once we are again compatible with it)
- Installation process is just unzipping the downloaded file
- When using in Java context: Set preference "Installed JRE" to the installed JDK (this is also required to run our traffic light example)

The current problem is that when SCT is downloaded, the traffic light example does not work out of the box when not setting the JRE preference. This should be documented.

**Comment by RainerKlute** [comment] 2016-05-25 10:16
Won't be worth the effort to document the JDK 1.8 depency, since that's just a bug we are about to fix.

**Comment by RainerKlute** [comment] 2016-06-21 17:08
Seems no JDK is needed at all. JRE is sufficient.

**Comment by RainerKlute** [comment] 2016-06-22 10:20
Can't reproduce the traffic light example problem. The example works for me without having to fiddle around with any JRE preferences.

**Comment by RainerKlute** [comment] 2016-06-22 10:20
Fixed with pull request #773.

**Comment by RainerKlute** [comment] 2016-06-23 11:08
Section on the JRE not found problem added with pull request #776.

**Closed** 2016-06-23 12:05 UTC
Labels: Comp-Documentation
