### ISSUE TITLE
New SCT model doesn't show in editor

### ISSUE THREAD

**Issue by bbpaulvanharen** [Yakindu/statecharts#3018] opened 2020-02-27 09:35 UTC
When creating a new statechart model, a non-functioning screen is editor window. The editor window doesn't display the filename, and has an inactive canvas, see screenshot. 
In the project explorer, the properties of the newly created statechart model are available. 

As a test, I've copied the contents an existing model into the new model (file based copy on file system level). In that case, the editor is opening correctly and showing contents as usual.

Please note, I'm using Yakindu SCT v 3.5.10 on Eclipse 2019-12 on Kubuntu 18.04 LTS.

Attachments:
Screenshot.png showing the inactive editor
![Screenshot_20200227_101823](https://user-images.githubusercontent.com/60341591/75430903-506e1680-594c-11ea-85da-ad9a4ada0869.png)
* (https://github.com/Yakindu/statecharts/files/4260735/eclipse.log) the logfile produced by the eclipse session
* (https://github.com/Yakindu/statecharts/files/4260738/default.sct.txt)
 the newly created model

**Comment by rherrmannr** [comment] 2020-02-28 10:30
How did you get the 3.5.10 version? Via update, update site, fresh install?
Currently, I can not reproduce the error. I've used an empty 2019-12 eclipse and installed SCT via update site on Ubuntu 18.04. 

New models work and I also can open your uploaded model.

**Comment by bbpaulvanharen** [comment] 2020-03-02 07:10
I've a fresh install of eclipse 2019-12. I installed SCT from the eclipse marketplace, i.e. the demo version. Immediately thereafter, I installed SCT from the "Install new software"  menu option, using the link that came along with the installation from the marketplace: http://updates.yakindu.com/statecharts/releases/

**Comment by rherrmannr** [comment] 2020-03-02 10:51
I can not reproduce this.

So, here is what I did:
- using the oomph installer and installed a clean 2019-12 
![image](https://user-images.githubusercontent.com/25480651/75669635-a1974680-5c7b-11ea-92db-963ffb2fded4.png)
- Manually installed the market place
![image](https://user-images.githubusercontent.com/25480651/75669708-c2f83280-5c7b-11ea-803b-5f9d05965082.png)
- Installed SCT via Marketplace
- Created a new model (working)
- Using "Install new Software" and added the update site to install YAKINDU Statechart Tools Standard Edition
- Still, the old model does work
- Added a new model that worked fine


Did I miss anything? Could you try out this solution, please?

**Comment by bbpaulvanharen** [comment] 2020-03-04 15:27
Hi,
Thank you for trying to reproduce my steps. I think you copied my scenario just fine. The issue remains; it works in your environment and not in mine. 
To be sure, I reinstalled a fresh Eclipse CDT through Oomph, version 2019-12, installed SCT from the marketplace and then again installed new software. In a new workspace, using the fresh install, I was able to reproduce the problem just fine.

I ran `eclipse > eclipse.log 2&>1` to grab all debug and logging output. Please find that
[eclipse.log](https://github.com/Yakindu/statecharts/files/4288067/eclipse.log) attached. I hope it contains some useful clues.

**Comment by andreasmuelder** [comment] 2020-03-16 08:36
Hi @bbpaulvanharen,
thanks, I checked the log, it seems that your installation does not contain the license management feature and thus some classes could not be loaded. Since I couldn't reproduce it too I will close this issue - it seems to be a specific problem with your environment. As a workaround, you can install the Licence Management feature from our provided update site.

**Closed by andreasmuelder** 2020-03-16 08:36 UTC
