### ISSUE TITLE
Statechart Tree view shows unnecessary "Annotatable Element" and "Type Specifier"

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2600] opened 2019-01-16 12:14 UTC
Title:
![image](https://user-images.githubusercontent.com/15799654/51248493-95c1c580-1990-11e9-9dba-57e7af7eee7d.png)

**Comment by andreasmuelder** [comment] 2019-01-16 13:31
duplicate of https://github.com/Yakindu/statecharts/issues/2607

**Closed by andreasmuelder** 2019-01-16 13:31 UTC
