### ISSUE TITLE
Transitions and error markers are always drawn on top

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1527] opened 2017-07-24 11:31 UTC
Top-level regions can overlap each other, and the region on top should cover everything below it. However, transitions and error markers of a covered region are always drawn on top of everything, no matter they should be covered.

**Comment by BeckmaR** [comment] 2017-07-26 13:59
Duplicate of #831 which was closed by @svenjawendler, reopening that one again

**Closed by BeckmaR** 2017-07-26 13:59 UTC
Labels: Comp-Graphical Editor, is-Bug, Status-Duplicate
