### ISSUE TITLE
Welcome page is outdated. Missing some features.

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2156] opened 2018-07-25 11:54 UTC
Missing:
- SCTUnit
- Coverage
- Rename to from deep C Integration to depp C/C++ Integration
- Missing examples. There are only two listed
- scxml as pro code generator

Copyright is outdated ```Copyright © 2017 itemis AG```

![grafik](https://user-images.githubusercontent.com/25480651/43199380-05526430-9012-11e8-9e69-5fd2269246b8.png)

**Comment by tkutz** [comment] 2018-07-28 16:40
Closed as duplicate of https://github.com/Yakindu/sctpro/issues/1125

**Closed by tkutz** 2018-07-28 16:40 UTC
