### ISSUE TITLE
multi step execution semantics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#102] opened 2015-04-24 13:34 UTC
```
Which features should be added?
1.  multi step execution semantics

MUlti step execution semantics will allow states to trigger events that will be 
processed in next run cycle.

For more information please see
https://groups.google.com/forum/#!topic/yakindu-user/O9W7XJeIpcU
and
https://groups.google.com/forum/#!msg/yakindu-user/wgkUHokZDZ0/aJt7BJffo7MJ


```

Original issue reported on code.google.com by `dimitris...@gmail.com` on 1 Apr 2015 at 1:01

**Comment by daemacles** [comment] 2016-08-05 16:26
Hi, I am looking for exactly this sort of behavior as well.  Are multi step execution semantics still on the roadmap?

Thanks

**Comment by terfloth** [comment] 2016-08-06 20:48
Yes, it is on the roadmap.

**Comment by tkutz** [comment] 2020-03-04 10:03
Closed as duplicate of https://github.com/Yakindu/statecharts/issues/2568

Super step semantic is implemented for the interpreter and all major code generators (C, C++, Python, Java) in version 4.0.

**Closed by tkutz** 2020-03-04 10:03 UTC
Labels: Comp-Graphical Editor, Prio-Medium, is-Feature-Request
