### ISSUE TITLE
Can you pass comments from state chart through to generated code?

### ISSUE THREAD

**Issue by robfox1976** [Yakindu/statecharts#1075] opened 2016-11-10 10:59 UTC
I think it would be very useful to be able to have comments that are in the state chart passed through to the generated code.

I'm not sure if there is any way of doing this?

**Comment by stmork** [comment] 2016-11-10 11:31
+1

**Comment by andreasmuelder** [comment] 2016-11-10 11:39
This is a duplicate of https://github.com/Yakindu/statecharts/issues/190

**Comment by andreasmuelder** [comment] 2016-11-10 11:41
This would be very useful indeed, it has to be defined where to generate the comments  We are open to any suggestions. Closing this as duplicate.

**Closed by andreasmuelder** 2016-11-10 11:41 UTC
