### ISSUE TITLE
Shapes disarranged after moving project

### ISSUE THREAD

**Issue by Prokli** [Yakindu/statecharts#144] opened 2015-10-18 11:35 UTC
I tried to copy an entire Yakindu project from one to another PC (just a simple copy & past). 
When I open this project on the second PC all shapes and transition pointers are complete disarranged. 
Both PCs are connected to monitors keeping a screen resolution of 1920 x 1080. I copied all files of my project on PC 1.
OS on PC1 ist Windows 7 (Prof) and OS on PC2 is Win 8.1

**Comment by terfloth** [comment] 2016-01-06 13:30
Take a closer look at symptoms. Problems are also known across different target OSs

**Comment by andreasmuelder** [comment] 2018-09-18 07:43
This is related to different font scaling settings on windows. Fixed with the latest release for windows, still an issue with mixed platforms.

Closing as duplicate of https://github.com/Yakindu/statecharts/issues/735

**Closed by andreasmuelder** 2018-09-18 07:43 UTC
Labels: Comp-Graphical Editor, Prio-Medium, is-Bug
