### ISSUE TITLE
What is bug????????????

### ISSUE THREAD

**Issue by hongsonitptit** [Yakindu/statecharts#1010] opened 2016-10-06 09:48 UTC
Hello,
I have a state chart diagram as bellow image:
![simple](https://cloud.githubusercontent.com/assets/5134089/19147789/ef340f34-8be3-11e6-9b46-cc5773cf5d0f.png)
After run simulation success I generate it to C++ source code and do:
1. call raiseOnA()
2. call raiseOnB()
3. call raiseOffB()
4. call raiseOnB()
5. call runCycle()
6. show state --> It's state is OFF not ON as my logic???
Why???
If I execute:
1. call raiseOnA()
2. call raiseOnB()
**3. call runCycle()** // difference
4. call raiseOffB()
5. call raiseOnB()
6. call runCycle()
7. show state --> It's state is ON correctly!!!
I do not understand what did the state tool do :|

**Comment by andreasmuelder** [comment] 2016-10-06 12:06
closing this as duplicate of #1003
If you have any questions regarding statechart tools, you can use our user group:
https://groups.google.com/forum/#!forum/yakindu-user

**Closed by andreasmuelder** 2016-10-06 12:06 UTC
