### ISSUE TITLE
Unclear error message when declaring namespace after annotations

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2348] opened 2018-10-17 12:33 UTC
The error message just rants about "missing EOF" which might indicate that this statement belongs to the end of the spec sec. Instead, it belongs to the top.

**Comment by tkutz** [comment] 2018-10-29 08:08
This is a duplicate of https://github.com/Yakindu/statecharts/issues/2203

**Closed by tkutz** 2018-10-29 08:08 UTC
Labels: Comp-Graphical Editor, is-Usability-Issue
